

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    #url: jdbc:mysql://localhost:3306/mpfe
    url: jdbc:h2:mem:refillappdb
    username : sa
    initialization-mode: always
  jackson:
    default-property-inclusion: non-null
    #username: demo
    #password: 7
    
logging:
  level:
    org:
      springframework: info
      hibernate:
        type: trace




server:
  servlet:
    context-path: /refillappdb
  port: 8454
  
Exception:
  message: Invalid Token